name: Deploy ServiceNow App with Pipeline Steps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SN_INSTANCE: ${{ secrets.SN_INSTANCE_URL }}
      SN_USERNAME: ${{ secrets.SN_USERNAME }}
      SN_PASSWORD: ${{ secrets.SN_PASSWORD }}
      APP_SCOPE: x_1761963_ci_cd_pi
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Create Pipeline Steps (if API available)
        run: |
          curl -X POST "$SN_INSTANCE/api/sn_cicd/pipeline/environments" \
            --user "$SN_USERNAME:$SN_PASSWORD" \
            --header "Content-Type: application/json" \
            --data '{
              "pipeline_name": "NameOfYourPipeline",
              "environments": [
                { "name": "Dev", "order": 1 },
                { "name": "Test", "order": 2 },
                { "name": "Prod", "order": 3 }
              ]
            }' || echo "Environment creation step (if exists) failed or skipped"

      - name: Apply Remote Changes
        run: |
          curl -X POST "$SN_INSTANCE/api/sn_cicd/apply_changes" \
            --user "$SN_USERNAME:$SN_PASSWORD" \
            --header "Content-Type: application/json" \
            --data '{
              "application_scope": "'"$APP_SCOPE"'",
              "branch_name": "'"$BRANCH_NAME"'"
            }'

      - name: Publish Application
        run: |
          curl -X POST "$SN_INSTANCE/api/sn_cicd/publish" \
            --user "$SN_USERNAME:$SN_PASSWORD" \
            --header "Content-Type: application/json" \
            --data '{
              "application_scope": "'"$APP_SCOPE"'"
            }'

      - name: Install Application
        run: |
          curl -X POST "$SN_INSTANCE/api/sn_cicd/install" \
            --user "$SN_USERNAME:$SN_PASSWORD" \
            --header "Content-Type: application/json" \
            --data '{
              "application_scope": "'"$APP_SCOPE"'"
            }'
