name: Deploy to ServiceNow Environment

on:
  push:
    branches:
      - POCBranch
  workflow_dispatch:  # Enables manual execution from the GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ServiceNow Change Request
        id: create_change
        uses: ServiceNow/servicenow-devops-change@main # Example action, actual action might differ
        with:
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          username: ${{ secrets.SN_USERNAME }}
          password: ${{ secrets.SN_PASSWORD }}
          change-request-data: |
            {
              "short_description": "Deployment for ${{ github.sha }}",
              "description": "Automated deployment triggered by GitHub Actions.",
              "assignment_group": "Development",
              "implementation_plan": "Deploy application changes.",
              "backout_plan": "Rollback to previous version.",
              "test_plan": "Execute automated tests."
            }

      - name: Perform Deployment Steps
        run: |
          echo "Executing deployment script..."
          # Add your actual deployment commands here
          # For example: deploy to a server, update configurations, etc.

      - name: Update ServiceNow Deployment Status
        uses: ServiceNow/servicenow-devops-update-deployment@main # Example action
        with:
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          username: ${{ secrets.SN_USERNAME }}
          password: ${{ secrets.SN_PASSWORD }}
          change-request-sys-id: ${{ steps.create_change.outputs.sys_id }}
          status: "Deployed"
