name: ServiceNow GitHub Actions Demo

on:
  push:
    branches:
      - POCBranch
  workflow_dispatch:  # Enables manual execution from the GitHub UI

jobs:
  build:
    # Purpose: Apply Remote Changes on Dev, then Publish the app
    name: Publish from Dev
    runs-on: ubuntu-latest

    steps:
      - name: Enable debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-publish-app@2.0.1
        env:
          nowUsername: ${{ secrets.SN_USERNAME }}
          nowPassword: ${{ secrets.SN_PASSWORD }}
          nowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
          appSysID: ${{ secrets.SN_APP_SYSID }}

      - name: ServiceNow CI/CD Publish App
        id: publish_app
        uses: ServiceNow/sncicd-publish-app@2.0.0
        with:
          versionTemplate: 1.1
          versionFormat: template
          # incrementBy: X  # Optional increment
        env:
          nowUsername: ${{ secrets.SN_USERNAME }}
          nowPassword: ${{ secrets.SN_PASSWORD }}
          nowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
          appSysID: ${{ secrets.SN_APP_SYSID }}

    outputs:
      publishversion: ${{ steps.publish_app.outputs.newVersion }}

  deployprod:
    needs: build
    name: Deploy to Prod
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
      - name: ServiceNow CI/CD Install App
        id: install_app_prod
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.build.outputs.newVersion }}
          # baseAppVersion: '1.2.3'  # Optional
          # autoUpgradeBaseApp: true  # Optional
        env:
          nowUsername: ${{ secrets.SN_USERNAME }}
          nowPassword: ${{ secrets.SN_PASSWORD }}
          nowInstallInstance: ${{ secrets.SN_PROD_INSTANCE }}
          appSysID: ${{ secrets.SN_APP_SYSID }}
