name: ServiceNow GitHub Actions Demo 2

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
    build:
        # Purpose of this job is to Apply Remote Changes for the branch triggering
        # the pipeline build to the Dev instance, then publish the application to
        # app repo using the template versioning format.
        name: Publish from Dev
        runs-on: ubuntu-latest
        # Below line can be used to set conditionals for modifying your pipeline as needed.
        if: ${{ github.event_name == 'pull_request'}}
            
        steps:
            - name: ServiceNow CI/CD Apply Changes
              uses: ServiceNow/sncicd-apply-changes@1.0.0
              env:
                    snowUsername: ${{ secrets.SN_USERNAME }}
                    snowPassword: ${{ secrets.SN_PASSWORD }}
                    snowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
                    appSysID: ${{ secrets.SN_APP_SYSID }}

            - name: ServiceNow CI/CD Publish App
              id: publish_app
              uses: ServiceNow/sncicd-publish-app@1.0.0
              with:
                versionTemplate: 1.1
                versionFormat: template
              env:
                    snowUsername: ${{ secrets.SN_USERNAME }}
                    snowPassword: ${{ secrets.SN_PASSWORD }}
                    snowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
                    appSysID: ${{ secrets.SN_APP_SYSID }}
                
        # This is required to pass the version number output from Publish App 
        # to the input for Install App in the next job! This is because the jobs 
        # run on different Linux instances, so without this Install App won't know
        # what to install.
        outputs:
            publishversion: ${{ steps.version.outputs.publishversion }}
