name: Deploy App to ServiceNow

on:
  push:
    branches:
      - main

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    env:
      SN_INSTANCE: https://dev306629.service-now.com
      SN_USERNAME: ${{ secrets.SN_USERNAME }}
      SN_PASSWORD: ${{ secrets.SN_PASSWORD }}
      APP_SCOPE: "your_app_scope_here"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Apply Changes to Dev
        uses: ServiceNow/sncicd-apply-changes@v3
        with:
          instance_url: ${{ env.SN_INSTANCE }}
          username: ${{ env.SN_USERNAME }}
          password: ${{ env.SN_PASSWORD }}
          app_scope: ${{ env.APP_SCOPE }}
          branch_name: ${{ github.ref_name }}

      - name: Install App
        uses: ServiceNow/sncicd-install-app@v3
        with:
          instance_url: ${{ env.SN_INSTANCE }}
          username: ${{ env.SN_USERNAME }}
          password: ${{ env.SN_PASSWORD }}
          app_scope: ${{ env.APP_SCOPE }}
          branch_name: ${{ github.ref_name }}

      - name: Run Tests
        uses: ServiceNow/sncicd-tests-run@v3
        with:
          instance_url: ${{ env.SN_INSTANCE }}
          username: ${{ env.SN_USERNAME }}
          password: ${{ env.SN_PASSWORD }}
          app_scope: ${{ env.APP_SCOPE }}
